#!/usr/bin/env bash
StartFsync() {
    nodeExists=`which node 2>/dev/null`
    rootDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
    log=$rootDir/fsync.log
    currentDir=`pwd`
    touch $log
    if [ -z $nodeExists ]; then
        node=$HOME/node/bin/node
        $node $rootDir >> $log &>> $log &    
    else
        node $rootDir >> $log &>> $log &
    fi
    echo -e "\033[36;4mFsync Started\033[0m"
    echo $! > $rootDir/fsync.pid
}
StartFsync $@
exit 0
