#!/usr/bin/env bash

WatchPulse()
{
	WatchIgnore=($(cat ./.watchignore))
	inotifywait -mr --timefmt '%d/%m/%y %H:%M' --format '%T %w %f' \
	-e close_write . | while read date time dir file; do
		updateFile=${file}
		WatchCompare=(${WatchIgnore[@]##"$updateFile"})
		if [ ${#WatchCompare[@]} -ne ${#WatchIgnore[@]} ];then
			#echo skipping $updateFile
			continue
		fi
		#convert absolute path to relative
		#updateFileREL=`echo "$FILECHANGE" | sed 's_'$curPath'/__'`
		echo -e "${time}::\033[0;33mFile updated: $updateFile\033[0;m"
        pkill node && node ~/fsync
	done
}

WatchPulse

